### ISSUE TITLE
Could be possible to setup the Taskforce Token when booting on premises

### ISSUE THREAD

**Issue by antoinelyset** [taskforcesh/taskforce-connector#110]
To help deploy our on premises version it would help to be able to set the Taskforce Token from an environment variable.

```yaml
services:
  backend:
    image: docker.taskforce.sh/onprem/dashboard:1.6.0
    restart: always
    ports:
      - "9876:9876"
    environment:
      LICENSE_KEY: ${LICENSE_KEY}
      HOST: ${HOST}
	  ....
      TASKFORCE_TOKEN: ${TASKFORCE_TOKEN}
```
