### ISSUE TITLE
Metrics not working

### ISSUE THREAD

**Issue by kevin-coelho** [taskforcesh/taskforce-connector#46]
Bull version: 4.8.1
Taskforce-connector version: 1.17.0

Instance information:
- docker compose with the following:
```
  taskforce-connector:
    build: https://github.com/taskforcesh/taskforce-connector.git#master
    container_name: taskforce-connector
    env_file:
      - .env.docker.development
    environment:
      TASKFORCE_CONNECTION: "local-dev-redis"
      REDIS_HOST: '127.0.0.1'
    command: taskforce --name local-dev-redis
    depends_on:
      - redis
 ```

Observed issue: no metrics available

![Screen Shot 2022-03-22 at 6 52 58 PM](https://user-images.githubusercontent.com/13863650/159606187-2732d1f3-5679-4d69-9143-cfe3fd01b400.png)

Jobs correctly show in other tabs
![Screen Shot 2022-03-22 at 6 53 21 PM](https://user-images.githubusercontent.com/13863650/159606230-8d7e507a-2931-4017-9d17-7eacc9c2cbe8.png)

Redis has metrics data
```
127.0.0.1:6379> lrange "bull:SensorQueue:metrics:failed:data" 0 -1
 1) "12"
 2) "11"
 3) "14"
 4) "10"
 5) "12"
 6) "12"
 7) "11"
 8) "12"
 9) "12"
10) "11"
11) "13"
12) "10"
13) "12"
14) "11"

127.0.0.1:6379> keys bull:SensorQueue:metrics:*
1) "bull:SensorQueue:metrics:failed"
2) "bull:SensorQueue:metrics:failed:data"
```

What further steps should I take to diagnose this, and any ideas about a fix?
